# Base image
FROM node:latest as build

# Working directory
WORKDIR /app

# Copy code into container
COPY . .

# Install dependencies and build app
RUN npm install
RUN npm install -g vite
RUN npm run build

# Production image
FROM nginx:latest

# Copy built app into container
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]