FROM mongo:latest

WORKDIR /usr/src/data

EXPOSE 27017

COPY backend/lieux-de-tournage-a-paris.json /lieux-de-tournage-a-paris.json
COPY users.json /users.json

CMD mongoimport --host mongodb --db projectdb --collection locations --file /lieux-de-tournage-a-paris.json --jsonArray && mongoimport --host mongodb --db projectdb --collection users --file /users.json