version: '3'

services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    restart: unless-stopped
    ports:
      - 4173:4173
    depends_on:
      - backend
    networks:
      - webAppNetwork

  backend:
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - JWT_SECRET=securewebdev
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - webAppNetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongo/mongo-entrypoint:/docker-entrypoint-initdb.d
      - ./mongo/data.json:/data.json
      - ./mongo/users.json:/users.json
      - project-db:/data/db
    networks:
      - webAppNetwork
    command: mongod; /bin/bash /docker-entrypoint-initdb.d/seed.sh

networks:
  webAppNetwork:
    driver: bridge

volumes:
  project-db: